### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by SebastianStehle**
I have found this library: https://github.com/AngleSharp/AngleSharp.Diffing

It allows to implement HTML diffing. But we usually render a lot of extra things, therefore I made 2 changes:

* Add a "plain" attribute to mjml to render everything just plain without the default html, head, body and so on.
* Add a few methods to disable all helpers in the tests (for head components).

### CODE REVIEW

**Review by LiamRiddell — APPROVED** [review]
I really like this. It allows us to properly implement more thorough testing. Great find and implementation :)

**Comment by LiamRiddell** [comment]
Once merged, I'll update tests in `<mj-text>` and `<mj-button>` branches!

**Comment by SebastianStehle** [comment]
What do you think about the plain attribute or would you just create a test component?

**Comment by LiamRiddell** [comment]
> What do you think about the plain attribute or would you just create a test component?

I prefer the idea of test component. I think it fits in nicely with the rest of the project.

**Comment by LiamRiddell** [comment]
I forgot to hit submit. :( The `<mjml-test>` looks good. 👍

**Pull request merged**
