### PR TITLE
Types

### PR DESCRIPTION
**Pull request by SebastianStehle**
I have implemented the types (former AttributeValues) and renamed them to types to be closer to Mjml.

Most types are super easy, thanks to unit parser and composition.

I also realized that there is some type of cleanup. At least the color type implements something like this in MJML. So I have added the same. I did not went through all the code to find the place, but I am sure it works like I have described.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Closes #19

**Review by LiamRiddell — APPROVED** [review]
Nice implementation. As mentioned by yourself. We'll need to refactor existing code on my branches but that's easy enough. It looks like the blast radius would be the Allowed and Default attributes.

**Comment by SebastianStehle** [comment]
> It looks like the blast radius would be the Allowed and Default attributes.

What do you mean with that?

**Comment by LiamRiddell** [comment]
Apologies, ignore my message. I'm happy to merge.

**Pull request merged**
