### PR TITLE
Started with validation.

### LINKED ISSUE #15: Validation: Allowed attributes

### LINKED ISSUE #16: Validation: Parents

### LINKED ISSUE #17: Validation: Parents (Root, no parent)

### LINKED ISSUE #18: Required mj-body

### PR DESCRIPTION
**Pull request by SebastianStehle**
I started with the validation. In theory is is feature complete. But....

* I have not tested it yet.
* I am not sure what strict and so on means. Here is is just an improvement from no-costs (skip) to expensive (strict).

Closes #15
Closes #16 
Closes #17 
Closes #18

### CODE REVIEW

**Review by Wampir0990 — APPROVED** [review]

**Comment by SebastianStehle** [comment]
Hi @Wampir0990 , who are you? Do you wanna help?

**Comment by SebastianStehle** [comment]
Could be, I have seen a few guys / bots from Russia.

**Comment by SebastianStehle** [comment]
I have added tests. It is done @LiamRiddell

**Comment by SebastianStehle** [comment]
Please review.

**Pull request merged**
